---
- hosts: all
  roles:

  # osx config
  - role: dock
    apps:
    - /Applications/Atom.app
    - /Applications/iTerm.app
    - /Applications/Dash.app
    folders:
    - path: ~/
    - path: ~/Documents
    - path: ~/Downloads
      sort: datemodified
  - role: dashboard
    disabled: YES

  # cli
  # shell tooling
  - role: git
    git_user_name: headmin
    git_user_email: 
  - role: legit
  - role: hub
#  - role: brew_package
#    package_name: vim
  ## languages
  - role: brew_package
    package_name: node
  - role: rbenv
  - role: npm_package
    package_name: grunt
  - role: npm_package
    package_name: bower
#  - role: cask_package
#    package_name: java
  ## databases
#  - role: brew_package
#    package_name: postgres
  - role: brew_package
    package_name: mongodb
  ## deployment
  - role: brew_package
    package_name: heroku-toolbelt
  # - role: brew_package
  #   package_name: ansible # Hey ! Already there !

  # gui
  ## text editors
  - role: cask_package
    package_name: atom
